function getNav(){var b=$("ul.main-navigation, ul[role=main-navigation]").before('<fieldset class="mobile-nav">'),a=$("fieldset.mobile-nav").append("<select>");a.find("select").append('<option value="">Navigate&hellip;</option>');var c=function(b,c){a.find("select").append('<option value="'+this.href+'">&raquo; '+$(this).text()+"</option>")};b.find("a").each(c);$("ul.subscription a").each(c);a.find("select").bind("change",function(a){a.target.value&&(window.location.href=a.target.value)})}
function addSidebarToggler(){$("body").hasClass("sidebar-footer")||($("#content").append('<span class="toggle-sidebar"></span>'),$(".toggle-sidebar").bind("click",function(a){a.preventDefault();$("body").hasClass("collapse-sidebar")?$("body").removeClass("collapse-sidebar"):$("body").addClass("collapse-sidebar")}));var b=$("aside.sidebar > section");1<b.length&&b.each(function(a,c){3<=b.length&&0===a%3&&$(c).addClass("first");var f=(a+1)%2?"odd":"even";$(c).addClass(f)});3<=b.length&&$("aside.sidebar").addClass("thirds")}
function testFeatures(){$(["maskImage"]).map(function(b,a){Modernizr.testAllProps(a)?$("html").addClass(a):$("html").addClass("no-"+a)});"placeholder"in document.createElement("input")?$("html").addClass("placeholder"):$("html").addClass("no-placeholder")}
function addCodeLineNumbers(){"Microsoft Internet Explorer"!==navigator.appName&&$("div.gist-highlight").each(function(b){for(var a='<pre class="line-numbers">',c=$(".line",b).length,f=1;f<=c;f++)a+='<span class="line-number">'+f+"</span>\n";a='<table><tbody><tr><td class="gutter">'+a+'</pre></td><td class="code"><pre>'+$("pre",b).html()+"</pre></td></tr></tbody></table>";$(b).html(a)})}
function flashVideoFallback(){$("video").each(function(b,a){a=$(a);if(!Modernizr.video.h264&&swfobject.getFlashPlayerVersion()||-1!==window.location.hash.indexOf("flash-test"))a.children("source[src$=mp4]").first().map(b,function(b){b=$(b).attr("src");var f="video_"+Math.round(1+1E5*Math.random()),l=a.attr("width"),r=parseInt(a.attr("height"),10)+30;a.after('<div class="flash-video"><div><div id='+f+">");swfobject.embedSWF("/assets/jwplayer/player.swf",f,l,r+30,"9.0.0",{file:b,image:a.attr("poster"),
skin:"/assets/jwplayer/glow/glow.xml"},{movie:b,wmode:"opaque",allowfullscreen:"true"})}),a.remove()})}function wrapFlashVideos(){$("object").each(function(b,a){$(a).find("param[name=movie]").length&&$(a).wrap('<div class="flash-video">')});$("iframe[src*=vimeo],iframe[src*=youtube]").wrap('<div class="flash-video">')}
function renderDeliciousLinks(b){for(var a="<ul>",c=0,f=b.length;c<f;c++)a+='<li><a href="'+b[c].u+'" title="Tags: '+(""==b[c].t?"":b[c].t.join(", "))+'">'+b[c].d+"</a></li>";a+="</ul>";$("#delicious").html(a)}$("document").ready(function(){testFeatures();wrapFlashVideos();flashVideoFallback();addCodeLineNumbers();getNav();addSidebarToggler()});
(function(b){function a(){l.content="width=device-width,minimum-scale="+f[0]+",maximum-scale="+f[1];b.removeEventListener(c,a,!0)}var c="gesturestart",f=[1,1],l="querySelectorAll"in b?b.querySelectorAll("meta[name=viewport]"):[];(l=l[l.length-1])&&"addEventListener"in b&&(a(),f=[0.25,1.6],b.addEventListener(c,a,!0))})(document);
var swfobject=function(){function b(e,m,b){var c,f=a(b);if(k.wk&&312>k.wk)return c;if(f)if(typeof e.id==l&&(e.id=b),k.ie&&k.win){var g="",d;for(d in e)e[d]!=Object.prototype[d]&&("data"==d.toLowerCase()?m.movie=e[d]:"styleclass"==d.toLowerCase()?g+=' class="'+e[d]+'"':"classid"!=d.toLowerCase()&&(g+=" "+d+'="'+e[d]+'"'));d="";for(var h in m)m[h]!=Object.prototype[h]&&(d+='<param name="'+h+'" value="'+m[h]+'" />');f.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+g+">"+d+"</object>";
c=a(e.id)}else{h=p.createElement(r);h.setAttribute("type",s);for(var n in e)e[n]!=Object.prototype[n]&&("styleclass"==n.toLowerCase()?h.setAttribute("class",e[n]):"classid"!=n.toLowerCase()&&h.setAttribute(n,e[n]));for(g in m)m[g]!=Object.prototype[g]&&"movie"!=g.toLowerCase()&&(e=h,d=g,n=m[g],b=p.createElement("param"),b.setAttribute("name",d),b.setAttribute("value",n),e.appendChild(b));f.parentNode.replaceChild(h,f);c=h}return c}function a(e){var a=null;try{a=p.getElementById(e)}catch(b){}return a}
function c(e){var a=k.pv;e=e.split(".");e[0]=parseInt(e[0],10);e[1]=parseInt(e[1],10)||0;e[2]=parseInt(e[2],10)||0;return a[0]>e[0]||a[0]==e[0]&&a[1]>e[1]||a[0]==e[0]&&a[1]==e[1]&&a[2]>=e[2]?!0:!1}function f(a){return null!=/[\\\"<>\.;]/.exec(a)&&typeof encodeURIComponent!=l?encodeURIComponent(a):a}var l="undefined",r="object",s="application/x-shockwave-flash",x=window,p=document,q=navigator,k=function(){var a=typeof p.getElementById!=l&&typeof p.getElementsByTagName!=l&&typeof p.createElement!=l,
b=q.userAgent.toLowerCase(),c=q.platform.toLowerCase(),f=c?/win/.test(c):/win/.test(b),c=c?/mac/.test(c):/mac/.test(b),b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1,k=!+"\x0B1",g=[0,0,0],d=null;if(typeof q.plugins!=l&&typeof q.plugins["Shockwave Flash"]==r)!(d=q.plugins["Shockwave Flash"].description)||typeof q.mimeTypes!=l&&q.mimeTypes[s]&&!q.mimeTypes[s].enabledPlugin||(k=!1,d=d.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),g[0]=parseInt(d.replace(/^(.*)\..*$/,"$1"),10),g[1]=
parseInt(d.replace(/^.*\.(.*)\s.*$/,"$1"),10),g[2]=/[a-zA-Z]/.test(d)?parseInt(d.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if(typeof x.ActiveXObject!=l)try{var h=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");h&&(d=h.GetVariable("$version"))&&(k=!0,d=d.split(" ")[1].split(","),g=[parseInt(d[0],10),parseInt(d[1],10),parseInt(d[2],10)])}catch(n){}return{w3:a,pv:g,wk:b,ie:k,win:f,mac:c}}();return{embedSWF:function(a,m,f,p,q,g,d,h,n){var s={success:!1,id:m};if(k.w3&&!(k.wk&&312>k.wk)&&a&&m&&f&&
p&&q){var t={};if(h&&typeof h===r)for(var v in h)t[v]=h[v];t.data=a;t.width=f+"";t.height=p+"";a={};if(d&&typeof d===r)for(var w in d)a[w]=d[w];if(g&&typeof g===r)for(var u in g)typeof a.flashvars!=l?a.flashvars+="&"+u+"="+g[u]:a.flashvars=u+"="+g[u];c(q)&&(m=b(t,a,m),s.success=!0,s.ref=m)}n&&n(s)},ua:k,getFlashPlayerVersion:function(){return{major:k.pv[0],minor:k.pv[1],release:k.pv[2]}},hasFlashPlayerVersion:c,createSWF:function(a,c,f){if(k.w3)return b(a,c,f)},getQueryParamValue:function(a){var b=
p.location.search||p.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(null==a)return f(b);for(var b=b.split("&"),c=0;c<b.length;c++)if(b[c].substring(0,b[c].indexOf("="))==a)return f(b[c].substring(b[c].indexOf("=")+1))}return""}}}();
