name:        Nicolas Rinaudo
markdown:    kramdown
highlighter: rouge

collections:
  talks:
    output: true

  articles:
    output: true

defaults:
      -
        scope:
          path: "_articles" # an empty string here means all files in the project
        values:
          series: "NONE"

kramdown:
  input:     GFM
  hard_wrap: false

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
