name:        Nicolas Rinaudo
markdown:    kramdown
highlighter: rouge

collections:
  optics:
    output:   true
    title:    Optics from the ground up
    sequence: 1

kramdown:
  input:     GFM
  hard_wrap: false

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
