name:        Nicolas Rinaudo
markdown:    kramdown
highlighter: rouge

collections:
  optics:
    output:   true
    title:    Optics from the ground up
    sequence: 1

  typeclasses:
    output:   true
    title:    Type classes from the ground up
    sequence: 2

  recschemes:
    output:   true
    title:    An introduction to recursion schemes
    sequence: 3

kramdown:
  input:     GFM
  hard_wrap: false

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
