name: Blog
markdown: redcarpet
highlighter: pygments
baseurl:
excerpt_separator: <!--more-->

collections:
  tut:
    output: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
