name:        Nicolas Rinaudo
markdown:    kramdown
highlighter: rouge

collections:
  optics:
    output:   true
    title:    Optics from the ground up
    date:     2020-02-20
    talk:     optics
    sequence: 1

  typeclasses:
    output:   true
    title:    Type classes from the ground up
    date:     2020-05-29
    talk:     type_classes_from_the_ground_up
    sequence: 2

  recschemes:
    output:   true
    title:    An introduction to recursion schemes
    date:     2021-05-21
    talk:     introduction_to_recursion_schemes
    sequence: 3

  talks:
    output: true

kramdown:
  input:     GFM
  hard_wrap: false

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
