name: Blog
markdown: kramdown
highlighter: rouge
baseurl:
excerpt_separator: <!--more-->

kramdown:
  input: GFM
  hard_wrap: false

collections:
  tut:
    output: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
